name: build

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.19
          cache: true
      - run: go test -v ./...